site_name: CR-XactXtract_workspace Docs
theme:
  name: material
  features:
    - navigation.instant
    - content.code.copy
    - content.tabs.link
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - codehilite
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Design:
      - Specifications: design/specifications/index.md
      - ADR Index: design/adrs/index.md
  - Agent Workflows: agent-workflows.md
  - Repo Prompt XML Apply: repo-prompt-xml.md
  - Additional Docs:
      - Overview: overview.md
      - LLM Context: CR-XactXtract/llm-context.md
  - How-To:
      - iPhone Backup (iMessage): how-to/iphone-backup.md
      - Instagram ZIP: how-to/instagram-zip.md
      - PDF Ingestion: how-to/pdf-ingestion.md
      - Local Transcription: how-to/transcription-local.md
