site_name: ChatX Documentation
theme:
  name: material
  features:
    - navigation.instant
    - content.code.copy
    - content.tabs.link
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - codehilite
nav:
  - Home: index.md
  - Overview: overview.md
  - Architecture: architecture.md
  - Design:
      - Specifications: design/specifications/index.md
      - ADRs: design/adrs/index.md
  - Development:
      - Developer Guide: development/developer-guide.md
      - Test Strategy: development/test-strategy.md
      - Contributing: development/contributing.md
  - How-To:
      - iPhone Backup (iMessage): how-to/iphone-backup.md
      - Instagram ZIP: how-to/instagram-zip.md
      - PDF Ingestion: how-to/pdf-ingestion.md
      - Local Transcription: how-to/transcription-local.md
  - Operations:
      - Security Threat Model: operations/security-threat-model.md
      - Non-Functional Requirements: operations/non-functional-requirements.md
  - Reference:
      - Interfaces: interfaces.md
      - FAQ: reference/faq.md
      - Changelog: reference/changelog.md
      - Commands: reference/commands/index.md
  - Plans:
      - Extractor Hardening: plans/extractor-hardening.md
      - Wave 2: plans/wave2.md
  - Research:
      - Image Enrichment: research/image-enrichment.md
      - Image Psychology Model Plan: research/image-psychology-model-research-plan.md
  - Policies:
      - Code of Conduct: policy/code-of-conduct.md
      - Security & Reporting: policy/security.md
