version: "1.0.0"
description: "MCP Performance Monitoring Configuration"

metrics:
  context_usage:
    enabled: true
    warn_threshold: 0.7
    critical_threshold: 0.85
    check_interval: 60
    actions:
      warn: "log"
      critical: "compact"

  token_consumption:
    enabled: true
    track_per_server: true
    alert_on_spike: true
    spike_threshold: 5000
    baseline_period_days: 7
    actions:
      spike: "alert"

  cache_performance:
    enabled: true
    min_hit_ratio: 0.6
    track_misses: true
    eviction_strategy: "lru"
    compression_enabled: true
    actions:
      low_ratio: "optimize"

  server_latency:
    enabled: true
    max_acceptable_ms: 500
    track_by_region: false
    percentile_tracking: [50, 95, 99]
    actions:
      exceed: "alert"

  error_rates:
    enabled: true
    max_error_rate: 0.05
    track_by_server: true
    track_by_operation: true
    recovery_monitoring: true
    actions:
      exceed: "investigate"

memory_cache:
  enabled: true
  max_size_mb: 512
  ttl_seconds: 3600
  eviction_policy: "lru"
  warm_cache_patterns:
    - project_structure
    - recent_tasks
    - common_imports
    - api_patterns
    - code_style_rules
    - todo_templates

alerting:
  enabled: true
  channels:
    - log
    - dashboard
  severity_levels:
    - info
    - warning
    - error
    - critical
  escalation:
    enabled: false
    thresholds:
      consecutive_warnings: 3
      time_window_minutes: 15

reporting:
  enabled: true
  interval_hours: 24
  retention_days: 30
  formats: ["json", "markdown"]
  include_trends: true
  include_recommendations: true

dashboards:
  enabled: true
  port: 3001
  metrics_endpoint: "/metrics"
  health_endpoint: "/health"
  update_interval_seconds: 30

logging:
  level: "info"
  format: "structured"
  include_timestamps: true
  include_correlation_ids: true
  retention_days: 30

integration:
  openmemory:
    track_usage: true
    correlate_events: true
    privacy_mode: true
  conport:
    store_metrics: true
    enable_queries: true
    correlation_tracking: true
  sequential_thinking:
    analysis_enabled: true
    pattern_recognition: true
    recommendation_engine: true